export const subtitles = [
  "Our preferences :)",
  "Taste the rainbow",
  "Where flavors come alive",
  "From our kitchen to your taste buds",
  "Satisfy your cravings",
  "Experience the joy of flavor",
  "A delicious adventure awaits",
  "Indulge in our selection",
  "Pure delight in every bite",
  "The taste of happiness",
  "Elevate your taste buds",
  "Join the flavor revolution",
  "It's always a good time for a treat",
  "Where taste meets innovation",
  "Unleash your inner foodie",
  "Life is uncertain, dessert is a must",
  "A treat for every occasion",
  "Because life is too short for bad food",
  "Indulge in the sweet life",
  "The ultimate flavor experience",
  "Come for the food, stay for the company",
  "We put the yum in your day",
  "For the love of flavor",
  "Deliciousness guaranteed",
  "Sweet dreams are made of this",
  "We've got your taste buds covered",
  "Food that makes you smile",
  "Flavors you can't resist",
  "Come for the food, stay for the fun",
  "Join the taste revolution",
  "Satisfy your sweet tooth",
  "A taste of heaven",
  "The perfect treat for any occasion",
  "We are passionate about flavor",
  "Food that hits the spot",
  "Where every bite is a delight",
  "Taste the difference",
  "Dessert is always a good idea",
  "Your taste buds will thank you",
  "Where sweet meets savory",
  "Elevating your dining experience",
  "Life is too short for boring food",
  "We take flavor to the next level",
  "The sweetest spot in town",
  "From our kitchen to your table",
  "Where food is an art",
  "Join us for a flavor journey",
  "We believe in the power of good food",
  "Delicious food, good times, great memories",
  "Dine like royalty",
  "Experience the magic of flavor",
  "Because you deserve the best",
  "Taste the love in every bite",
  "Flavors that make your heart sing",
  "Where every meal is a celebration",
  "Your taste buds deserve it",
  "Life is better with good food",
  "Where flavor meets imagination",
  "A taste of happiness in every bite",
  "Where food meets artistry",
  "The perfect balance of sweet and savory",
  "Come for the food, stay for the experience",
  "Treat yourself to something special",
  "A culinary journey you won't forget",
  "Food that makes you feel good",
  "Flavors you won't find anywhere else",
  "We make every meal an event",
  "Elevate your taste experience",
  "Because life is too short for bland food",
  "Join us for a flavor adventure",
  "Satisfy your cravings in style",
  "We put the sparkle in your day",
  "Where every dish is a masterpiece",
  "A treat for all the senses",
  "Flavors that transport you",
  "Where food and friends come together",
  "Because you deserve to indulge",
  "Savor the moment with us",
  "Where sweet dreams become a reality",
  "Good food, good friends, great memories",
  "Your taste buds will be amazed",
  "Join us for a culinary journey",
  "Where every bite is a revelation",
  "We believe in the power of good food",
  "Delicious food, good times, great memories",
  "Dine like royalty",
  "Experience the magic of flavor",
  "Because you deserve the best",
  "Taste the love in every bite",
  "Flavors that make your heart sing",
  "Where every meal is a celebration",
  "Your taste buds deserve it",
  "Life is better with good food",
  "Where flavor meets imagination",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't oysters share their pearls? Because they're shellfish!",
  "Why did the banana go to the doctor? Because it wasn't peeling well!",
  "Why did the coffee file a police report? Because it got mugged!",
  "Why don't eggs tell jokes? Because they'd crack each other up!",
  "Why did the grape stop in the middle of the road? Because it ran out of juice!",
  "Why did the cookie go to the doctor? Because it was feeling crumbly!",
  "Why did the melon jump into the lake? Because it wanted to make a splash!",
];

export const searchMessages = (newValue: string) => {
  return [
    "What are you craving?",
    `Looking for ${newValue}?`,
    `Fancy results for: ${newValue}`,
    `The best results for: ${newValue}`,
    `Missing: ${newValue}? Not anymore!`,
    `Your search for ${newValue} ends here!`,
    `No need to search any further for ${newValue}!`,
    `Amazed by ${newValue} search results?`,
    `A world of possibilities with ${newValue}!`,
    `Your ${newValue} search!`,
    `Our exciting ${newValue} options!`,
  ];
};

export const randomMessage: string[] = [
  "Ready for a delicious surprise?",
  "Feeling adventurous? Try this recipe!",
  "Don't know what to cook? We've got you covered!",
  "Discover something new with this random recipe!",
  "Are you brave enough to try this random recipe?",
  "In the mood for something unexpected? Try this!",
  "Get ready to take your taste buds on a journey!",
  "Let fate decide what's for dinner with a random recipe!",
  "This recipe might just become your new favorite!",
  "This random recipe is sure to become a family favorite!",
  "No need to search any further for a random recipe!",
  "Embrace the unexpected and try this random recipe!",
  "Are you ready for a random recipe adventure?",
];
